/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/gaming/tips-for-palworld-server': RouteRecordInfo<'/posts/gaming/tips-for-palworld-server', '/posts/gaming/tips-for-palworld-server', Record<never, never>, Record<never, never>>,
    '/posts/learning/19_engine_string': RouteRecordInfo<'/posts/learning/19_engine_string', '/posts/learning/19_engine_string', Record<never, never>, Record<never, never>>,
    '/posts/learning/23_compress_string': RouteRecordInfo<'/posts/learning/23_compress_string', '/posts/learning/23_compress_string', Record<never, never>, Record<never, never>>,
    '/posts/learning/24_europe_championship': RouteRecordInfo<'/posts/learning/24_europe_championship', '/posts/learning/24_europe_championship', Record<never, never>, Record<never, never>>,
    '/posts/learning/31_ram_management': RouteRecordInfo<'/posts/learning/31_ram_management', '/posts/learning/31_ram_management', Record<never, never>, Record<never, never>>,
    '/posts/learning/35_traversing_binary_tree': RouteRecordInfo<'/posts/learning/35_traversing_binary_tree', '/posts/learning/35_traversing_binary_tree', Record<never, never>, Record<never, never>>,
    '/posts/learning/39_world_cup': RouteRecordInfo<'/posts/learning/39_world_cup', '/posts/learning/39_world_cup', Record<never, never>, Record<never, never>>,
    '/posts/learning/56_equal_polynomial': RouteRecordInfo<'/posts/learning/56_equal_polynomial', '/posts/learning/56_equal_polynomial', Record<never, never>, Record<never, never>>,
    '/posts/learning/9_phone_number': RouteRecordInfo<'/posts/learning/9_phone_number', '/posts/learning/9_phone_number', Record<never, never>, Record<never, never>>,
    '/posts/learning/a-K8s-training': RouteRecordInfo<'/posts/learning/a-K8s-training', '/posts/learning/a-K8s-training', Record<never, never>, Record<never, never>>,
    '/posts/learning/assembly': RouteRecordInfo<'/posts/learning/assembly', '/posts/learning/assembly', Record<never, never>, Record<never, never>>,
    '/posts/learning/bit_byte_and_information_storage': RouteRecordInfo<'/posts/learning/bit_byte_and_information_storage', '/posts/learning/bit_byte_and_information_storage', Record<never, never>, Record<never, never>>,
    '/posts/learning/build-lfs-with-wsl': RouteRecordInfo<'/posts/learning/build-lfs-with-wsl', '/posts/learning/build-lfs-with-wsl', Record<never, never>, Record<never, never>>,
    '/posts/learning/ccf201609_2_train_ticket': RouteRecordInfo<'/posts/learning/ccf201609_2_train_ticket', '/posts/learning/ccf201609_2_train_ticket', Record<never, never>, Record<never, never>>,
    '/posts/learning/csapp_bomblab': RouteRecordInfo<'/posts/learning/csapp_bomblab', '/posts/learning/csapp_bomblab', Record<never, never>, Record<never, never>>,
    '/posts/learning/deep-learning-from-scratch-cnn': RouteRecordInfo<'/posts/learning/deep-learning-from-scratch-cnn', '/posts/learning/deep-learning-from-scratch-cnn', Record<never, never>, Record<never, never>>,
    '/posts/learning/deep-learning-from-scratch-error-back-propagation': RouteRecordInfo<'/posts/learning/deep-learning-from-scratch-error-back-propagation', '/posts/learning/deep-learning-from-scratch-error-back-propagation', Record<never, never>, Record<never, never>>,
    '/posts/learning/deep-learning-from-scratch-learning-of-neural-network': RouteRecordInfo<'/posts/learning/deep-learning-from-scratch-learning-of-neural-network', '/posts/learning/deep-learning-from-scratch-learning-of-neural-network', Record<never, never>, Record<never, never>>,
    '/posts/learning/deep-learning-from-scratch-neural-network': RouteRecordInfo<'/posts/learning/deep-learning-from-scratch-neural-network', '/posts/learning/deep-learning-from-scratch-neural-network', Record<never, never>, Record<never, never>>,
    '/posts/learning/deep-learning-from-scratch-perception': RouteRecordInfo<'/posts/learning/deep-learning-from-scratch-perception', '/posts/learning/deep-learning-from-scratch-perception', Record<never, never>, Record<never, never>>,
    '/posts/learning/deep-learning-from-scratch-some-tricks-related-with-learning': RouteRecordInfo<'/posts/learning/deep-learning-from-scratch-some-tricks-related-with-learning', '/posts/learning/deep-learning-from-scratch-some-tricks-related-with-learning', Record<never, never>, Record<never, never>>,
    '/posts/learning/how-to-own-a-tricycle': RouteRecordInfo<'/posts/learning/how-to-own-a-tricycle', '/posts/learning/how-to-own-a-tricycle', Record<never, never>, Record<never, never>>,
    '/posts/learning/java-implement-array-list': RouteRecordInfo<'/posts/learning/java-implement-array-list', '/posts/learning/java-implement-array-list', Record<never, never>, Record<never, never>>,
    '/posts/learning/java-inheritance': RouteRecordInfo<'/posts/learning/java-inheritance', '/posts/learning/java-inheritance', Record<never, never>, Record<never, never>>,
    '/posts/learning/java-interface': RouteRecordInfo<'/posts/learning/java-interface', '/posts/learning/java-interface', Record<never, never>, Record<never, never>>,
    '/posts/learning/java-object-class': RouteRecordInfo<'/posts/learning/java-object-class', '/posts/learning/java-object-class', Record<never, never>, Record<never, never>>,
    '/posts/learning/java-thread': RouteRecordInfo<'/posts/learning/java-thread', '/posts/learning/java-thread', Record<never, never>, Record<never, never>>,
    '/posts/learning/java-thread-producer-and-consumer': RouteRecordInfo<'/posts/learning/java-thread-producer-and-consumer', '/posts/learning/java-thread-producer-and-consumer', Record<never, never>, Record<never, never>>,
    '/posts/learning/machine_level_representation_of_programs': RouteRecordInfo<'/posts/learning/machine_level_representation_of_programs', '/posts/learning/machine_level_representation_of_programs', Record<never, never>, Record<never, never>>,
    '/posts/learning/stc-beep-music': RouteRecordInfo<'/posts/learning/stc-beep-music', '/posts/learning/stc-beep-music', Record<never, never>, Record<never, never>>,
    '/posts/learning/write-a-roguelike-game-with-tcod-rs': RouteRecordInfo<'/posts/learning/write-a-roguelike-game-with-tcod-rs', '/posts/learning/write-a-roguelike-game-with-tcod-rs', Record<never, never>, Record<never, never>>,
    '/posts/log/2020.8.22': RouteRecordInfo<'/posts/log/2020.8.22', '/posts/log/2020/8/22', Record<never, never>, Record<never, never>>,
    '/posts/log/2020.8.26': RouteRecordInfo<'/posts/log/2020.8.26', '/posts/log/2020/8/26', Record<never, never>, Record<never, never>>,
    '/posts/log/hello-valaxy': RouteRecordInfo<'/posts/log/hello-valaxy', '/posts/log/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/log/move_to_github': RouteRecordInfo<'/posts/log/move_to_github', '/posts/log/move_to_github', Record<never, never>, Record<never, never>>,
    '/posts/log/welcome_Typecho': RouteRecordInfo<'/posts/log/welcome_Typecho', '/posts/log/welcome_Typecho', Record<never, never>, Record<never, never>>,
    '/posts/memory/20_years_old': RouteRecordInfo<'/posts/memory/20_years_old', '/posts/memory/20_years_old', Record<never, never>, Record<never, never>>,
    '/posts/memory/2021-middle': RouteRecordInfo<'/posts/memory/2021-middle', '/posts/memory/2021-middle', Record<never, never>, Record<never, never>>,
    '/posts/memory/24-1024': RouteRecordInfo<'/posts/memory/24-1024', '/posts/memory/24-1024', Record<never, never>, Record<never, never>>,
    '/posts/memory/after-two-months-in-shanghai': RouteRecordInfo<'/posts/memory/after-two-months-in-shanghai', '/posts/memory/after-two-months-in-shanghai', Record<never, never>, Record<never, never>>,
    '/posts/memory/drift-on-curves': RouteRecordInfo<'/posts/memory/drift-on-curves', '/posts/memory/drift-on-curves', Record<never, never>, Record<never, never>>,
    '/posts/memory/graduate-from-university': RouteRecordInfo<'/posts/memory/graduate-from-university', '/posts/memory/graduate-from-university', Record<never, never>, Record<never, never>>,
    '/posts/memory/take_ccf_examination': RouteRecordInfo<'/posts/memory/take_ccf_examination', '/posts/memory/take_ccf_examination', Record<never, never>, Record<never, never>>,
    '/posts/review/klein-no-tsubo-by-futari-okajima': RouteRecordInfo<'/posts/review/klein-no-tsubo-by-futari-okajima', '/posts/review/klein-no-tsubo-by-futari-okajima', Record<never, never>, Record<never, never>>,
    '/posts/review/peacock-could-we-see-dreams-come-true': RouteRecordInfo<'/posts/review/peacock-could-we-see-dreams-come-true', '/posts/review/peacock-could-we-see-dreams-come-true', Record<never, never>, Record<never, never>>,
    '/posts/review/read_a_song_of_ice_and_fire': RouteRecordInfo<'/posts/review/read_a_song_of_ice_and_fire', '/posts/review/read_a_song_of_ice_and_fire', Record<never, never>, Record<never, never>>,
    '/posts/review/read_kara_no_kyoukai': RouteRecordInfo<'/posts/review/read_kara_no_kyoukai', '/posts/review/read_kara_no_kyoukai', Record<never, never>, Record<never, never>>,
    '/posts/review/trying-to-analyze-dao-guan': RouteRecordInfo<'/posts/review/trying-to-analyze-dao-guan', '/posts/review/trying-to-analyze-dao-guan', Record<never, never>, Record<never, never>>,
    '/posts/things/a-toy-for-chatting-chamber': RouteRecordInfo<'/posts/things/a-toy-for-chatting-chamber', '/posts/things/a-toy-for-chatting-chamber', Record<never, never>, Record<never, never>>,
    '/posts/things/customize-email-domain': RouteRecordInfo<'/posts/things/customize-email-domain', '/posts/things/customize-email-domain', Record<never, never>, Record<never, never>>,
    '/posts/things/i3wm_config_backup': RouteRecordInfo<'/posts/things/i3wm_config_backup', '/posts/things/i3wm_config_backup', Record<never, never>, Record<never, never>>,
    '/posts/things/install_air_conditioner': RouteRecordInfo<'/posts/things/install_air_conditioner', '/posts/things/install_air_conditioner', Record<never, never>, Record<never, never>>,
    '/posts/things/install_dual_os': RouteRecordInfo<'/posts/things/install_dual_os', '/posts/things/install_dual_os', Record<never, never>, Record<never, never>>,
    '/posts/things/ninga-sound-trying-trae': RouteRecordInfo<'/posts/things/ninga-sound-trying-trae', '/posts/things/ninga-sound-trying-trae', Record<never, never>, Record<never, never>>,
    '/posts/things/some-linux-tips': RouteRecordInfo<'/posts/things/some-linux-tips', '/posts/things/some-linux-tips', Record<never, never>, Record<never, never>>,
    '/posts/writing/a_winter_day': RouteRecordInfo<'/posts/writing/a_winter_day', '/posts/writing/a_winter_day', Record<never, never>, Record<never, never>>,
    '/posts/writing/insects_awaken': RouteRecordInfo<'/posts/writing/insects_awaken', '/posts/writing/insects_awaken', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
